version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: appointment_system_db
    environment:
      POSTGRES_DB: appointment_system_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5555:5555"
    command: -p 5555
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
